# Brownie project configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html

# Project-specific settings
project_structure:
  contracts: contracts
  reports: reports
  scripts: scripts
  tests: tests

# Compiler settings
compiler:
  solc:
    # List of Solidity compiler versions to install
    version: 0.8.19
    # Remappings for imports (e.g., for OpenZeppelin)
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"

# Network settings
networks:
  # Default development network
  development:
    host: http://127.0.0.1:8545
    # Optional: mnemonic for accounts
    # mnemonic: "your-ganache-mnemonic-here"
    gas_limit: "max"
    gas_price: 0
    reverting_tx_gas_limit: "max"

  # Live network configurations (example)
  # mainnet:
  #   host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID

# Dependency management for packages like OpenZeppelin
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0

# Console settings
console:
  show_colors: true
  color_style: monokai